project:
  type: website
  output-dir: _site/en/stable
website:
  title: "Versioned Quarto"
  site-url: https://itcarroll.github.io/versioned-quarto/en/stable
  navbar:
    right:
      - href: https://itcarroll.github.io/versioned-quarto/
        text: stable
      - href: https://itcarroll.github.io/versioned-quarto/en/latest
        text: latest
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - guide.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
