name: Quarto Publish
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Prepare Worktree
        run: |
          git worktree add --track -B gh-pages _site origin/gh-pages
      - name: Render Stable
        uses: quarto-dev/quarto-actions/render@v2
      - name: Render Latest
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: latest
      - name: Publish
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cd _site
          git add -Af .
          git commit --message "quarto render"
          git push