name: Quarto Publish
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Stable
        uses: quarto-dev/quarto-actions/render@v2
      - name: Render Latest
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: latest
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
